@startuml
skinparam defaultFontName Arial

  "Azure.Core" --> "System.ClientModel"
  "Azure.Core" --> "Microsoft.Bcl.AsyncInterfaces"
  "Azure.Core" --> "System.Text.Encodings.Web"
  "Azure.Core" --> "System.Numerics.Vectors"
  "Azure.Core" --> "System.Memory.Data"
  "Azure.Core" --> "System.Diagnostics.DiagnosticSource"
  "Azure.Core" --> "System.Text.Json"
  "Azure.Core" --> "System.Threading.Tasks.Extensions"
  "System.ClientModel" --> "Microsoft.Extensions.Logging.Abstractions"
  "System.ClientModel" --> "Microsoft.Extensions.Hosting.Abstractions"
  "System.ClientModel" --> "Microsoft.Extensions.Configuration.Abstractions"
  "System.ClientModel" --> "System.Memory.Data"
  "System.ClientModel" --> "System.Diagnostics.DiagnosticSource"
  "System.ClientModel" --> "System.Text.Json"
  "Microsoft.Bcl.AsyncInterfaces" --> "System.Threading.Tasks.Extensions"
  "System.Text.Encodings.Web" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Text.Encodings.Web" --> "System.Memory"
  "System.Text.Encodings.Web" --> "System.Buffers"
  "System.Memory.Data" --> "System.Memory"
  "System.Memory.Data" --> "System.Text.Json"
  "System.Diagnostics.DiagnosticSource" --> "System.Memory"
  "System.Diagnostics.DiagnosticSource" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Text.Json" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Text.Json" --> "Microsoft.Bcl.AsyncInterfaces"
  "System.Text.Json" --> "System.Text.Encodings.Web"
  "System.Text.Json" --> "System.ValueTuple"
  "System.Text.Json" --> "System.Memory"
  "System.Text.Json" --> "System.Buffers"
  "System.Text.Json" --> "System.IO.Pipelines"
  "System.Text.Json" --> "System.Threading.Tasks.Extensions"
  "System.Threading.Tasks.Extensions" --> "System.Runtime.CompilerServices.Unsafe"
@enduml