@startuml
skinparam defaultFontName Arial

  "Azure.Core" --> "System.Threading.Tasks.Extensions"
  "Azure.Core" --> "System.Diagnostics.DiagnosticSource"
  "Azure.Core" --> "System.Memory.Data"
  "Azure.Core" --> "System.Numerics.Vectors"
  "Azure.Core" --> "Microsoft.Bcl.AsyncInterfaces"
  "Azure.Core" --> "System.Text.Json"
  "Azure.Core" --> "System.Text.Encodings.Web"
  "Azure.Core" --> "System.ClientModel"
  "System.Threading.Tasks.Extensions" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Diagnostics.DiagnosticSource" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Diagnostics.DiagnosticSource" --> "System.Memory"
  "System.Memory" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Memory" --> "System.Numerics.Vectors"
  "System.Memory" --> "System.Buffers"
  "System.Memory.Data" --> "System.Text.Json"
  "System.Memory.Data" --> "System.Memory"
  "System.Text.Json" --> "System.Threading.Tasks.Extensions"
  "System.Text.Json" --> "System.ValueTuple"
  "System.Text.Json" --> "System.Buffers"
  "System.Text.Json" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Text.Json" --> "Microsoft.Bcl.AsyncInterfaces"
  "System.Text.Json" --> "System.IO.Pipelines"
  "System.Text.Json" --> "System.Text.Encodings.Web"
  "System.Text.Json" --> "System.Memory"
  "Microsoft.Bcl.AsyncInterfaces" --> "System.Threading.Tasks.Extensions"
  "System.IO.Pipelines" --> "System.Threading.Tasks.Extensions"
  "System.IO.Pipelines" --> "System.Buffers"
  "System.IO.Pipelines" --> "System.Memory"
  "System.Text.Encodings.Web" --> "System.Runtime.CompilerServices.Unsafe"
  "System.Text.Encodings.Web" --> "System.Buffers"
  "System.Text.Encodings.Web" --> "System.Memory"
  "System.ClientModel" --> "Microsoft.Extensions.Logging.Abstractions"
  "System.ClientModel" --> "System.Diagnostics.DiagnosticSource"
  "System.ClientModel" --> "Microsoft.Extensions.Configuration.Abstractions"
  "System.ClientModel" --> "System.Memory.Data"
  "System.ClientModel" --> "System.Text.Json"
  "System.ClientModel" --> "Microsoft.Extensions.Hosting.Abstractions"
  "Microsoft.Extensions.Logging.Abstractions" --> "Microsoft.Extensions.DependencyInjection.Abstractions"
  "Microsoft.Extensions.Logging.Abstractions" --> "System.Buffers"
  "Microsoft.Extensions.Logging.Abstractions" --> "System.Diagnostics.DiagnosticSource"
  "Microsoft.Extensions.Logging.Abstractions" --> "System.Memory"
  "Microsoft.Extensions.DependencyInjection.Abstractions" --> "Microsoft.Bcl.AsyncInterfaces"
  "Microsoft.Extensions.DependencyInjection.Abstractions" --> "System.Threading.Tasks.Extensions"
  "Microsoft.Extensions.Configuration.Abstractions" --> "System.ValueTuple"
  "Microsoft.Extensions.Configuration.Abstractions" --> "Microsoft.Extensions.Primitives"
  "Microsoft.Extensions.Primitives" --> "System.Runtime.CompilerServices.Unsafe"
  "Microsoft.Extensions.Primitives" --> "System.Memory"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Extensions.FileProviders.Abstractions"
  "Microsoft.Extensions.Hosting.Abstractions" --> "System.Threading.Tasks.Extensions"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Extensions.Logging.Abstractions"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Extensions.Configuration.Abstractions"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Bcl.AsyncInterfaces"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Extensions.Diagnostics.Abstractions"
  "Microsoft.Extensions.Hosting.Abstractions" --> "Microsoft.Extensions.DependencyInjection.Abstractions"
  "Microsoft.Extensions.FileProviders.Abstractions" --> "Microsoft.Extensions.Primitives"
  "Microsoft.Extensions.Diagnostics.Abstractions" --> "System.Diagnostics.DiagnosticSource"
  "Microsoft.Extensions.Diagnostics.Abstractions" --> "System.Buffers"
  "Microsoft.Extensions.Diagnostics.Abstractions" --> "Microsoft.Extensions.Options"
  "Microsoft.Extensions.Diagnostics.Abstractions" --> "Microsoft.Extensions.DependencyInjection.Abstractions"
  "Microsoft.Extensions.Diagnostics.Abstractions" --> "System.Memory"
  "Microsoft.Extensions.Options" --> "System.ComponentModel.Annotations"
  "Microsoft.Extensions.Options" --> "Microsoft.Extensions.DependencyInjection.Abstractions"
  "Microsoft.Extensions.Options" --> "Microsoft.Extensions.Primitives"
  "Microsoft.Extensions.Options" --> "System.ValueTuple"
  "System.ComponentModel.Annotations" --> "System.ComponentModel"
  "System.ComponentModel.Annotations" --> "NETStandard.Library"
  "System.ComponentModel" --> "System.Runtime"
  "System.Runtime" --> "Microsoft.NETCore.Platforms"
  "System.Runtime" --> "Microsoft.NETCore.Targets"
  "NETStandard.Library" --> "System.Threading"
  "NETStandard.Library" --> "System.Diagnostics.Tracing"
  "NETStandard.Library" --> "System.Threading.Tasks"
  "NETStandard.Library" --> "System.AppContext"
  "NETStandard.Library" --> "System.Security.Cryptography.Primitives"
  "NETStandard.Library" --> "System.IO.Compression"
  "NETStandard.Library" --> "System.Text.Encoding"
  "NETStandard.Library" --> "System.IO.FileSystem"
  "NETStandard.Library" --> "System.Threading.Timer"
  "NETStandard.Library" --> "System.Runtime.Extensions"
  "NETStandard.Library" --> "System.Runtime.Handles"
  "NETStandard.Library" --> "System.Reflection.Extensions"
  "NETStandard.Library" --> "System.Runtime.InteropServices.RuntimeInformation"
  "NETStandard.Library" --> "System.Resources.ResourceManager"
  "NETStandard.Library" --> "System.Runtime"
  "NETStandard.Library" --> "System.Collections.Concurrent"
  "NETStandard.Library" --> "System.Collections"
  "NETStandard.Library" --> "System.IO.FileSystem.Primitives"
  "NETStandard.Library" --> "System.Runtime.InteropServices"
  "NETStandard.Library" --> "System.Security.Cryptography.X509Certificates"
  "NETStandard.Library" --> "System.Globalization.Calendars"
  "NETStandard.Library" --> "System.Diagnostics.Tools"
  "NETStandard.Library" --> "System.Globalization"
  "NETStandard.Library" --> "System.Linq.Expressions"
  "NETStandard.Library" --> "System.Net.Primitives"
  "NETStandard.Library" --> "System.Xml.XDocument"
  "NETStandard.Library" --> "System.Console"
  "NETStandard.Library" --> "System.Security.Cryptography.Encoding"
  "NETStandard.Library" --> "Microsoft.Win32.Primitives"
  "NETStandard.Library" --> "System.Xml.ReaderWriter"
  "NETStandard.Library" --> "System.Linq"
  "NETStandard.Library" --> "System.Text.RegularExpressions"
  "NETStandard.Library" --> "System.Reflection"
  "NETStandard.Library" --> "System.IO"
  "NETStandard.Library" --> "System.Security.Cryptography.Algorithms"
  "NETStandard.Library" --> "System.Net.Sockets"
  "NETStandard.Library" --> "System.Reflection.Primitives"
  "NETStandard.Library" --> "System.ObjectModel"
  "NETStandard.Library" --> "System.Diagnostics.Debug"
  "NETStandard.Library" --> "System.Net.Http"
  "NETStandard.Library" --> "Microsoft.NETCore.Platforms"
  "NETStandard.Library" --> "System.IO.Compression.ZipFile"
  "NETStandard.Library" --> "System.Runtime.Numerics"
  "NETStandard.Library" --> "System.Text.Encoding.Extensions"
  "System.Threading" --> "System.Runtime"
  "System.Threading" --> "System.Threading.Tasks"
  "System.Threading.Tasks" --> "Microsoft.NETCore.Platforms"
  "System.Threading.Tasks" --> "System.Runtime"
  "System.Threading.Tasks" --> "Microsoft.NETCore.Targets"
  "System.Diagnostics.Tracing" --> "Microsoft.NETCore.Platforms"
  "System.Diagnostics.Tracing" --> "System.Runtime"
  "System.Diagnostics.Tracing" --> "Microsoft.NETCore.Targets"
  "System.AppContext" --> "System.Threading"
  "System.AppContext" --> "System.Resources.ResourceManager"
  "System.AppContext" --> "System.Runtime"
  "System.AppContext" --> "System.Collections"
  "System.Resources.ResourceManager" --> "System.Runtime"
  "System.Resources.ResourceManager" --> "System.Reflection"
  "System.Resources.ResourceManager" --> "Microsoft.NETCore.Platforms"
  "System.Resources.ResourceManager" --> "System.Globalization"
  "System.Resources.ResourceManager" --> "Microsoft.NETCore.Targets"
  "System.Reflection" --> "System.Runtime"
  "System.Reflection" --> "Microsoft.NETCore.Targets"
  "System.Reflection" --> "Microsoft.NETCore.Platforms"
  "System.Reflection" --> "System.IO"
  "System.Reflection" --> "System.Reflection.Primitives"
  "System.IO" --> "System.Runtime"
  "System.IO" --> "Microsoft.NETCore.Platforms"
  "System.IO" --> "System.Threading.Tasks"
  "System.IO" --> "System.Text.Encoding"
  "System.IO" --> "Microsoft.NETCore.Targets"
  "System.Text.Encoding" --> "Microsoft.NETCore.Platforms"
  "System.Text.Encoding" --> "System.Runtime"
  "System.Text.Encoding" --> "Microsoft.NETCore.Targets"
  "System.Reflection.Primitives" --> "Microsoft.NETCore.Platforms"
  "System.Reflection.Primitives" --> "System.Runtime"
  "System.Reflection.Primitives" --> "Microsoft.NETCore.Targets"
  "System.Globalization" --> "Microsoft.NETCore.Platforms"
  "System.Globalization" --> "System.Runtime"
  "System.Globalization" --> "Microsoft.NETCore.Targets"
  "System.Collections" --> "Microsoft.NETCore.Platforms"
  "System.Collections" --> "System.Runtime"
  "System.Collections" --> "Microsoft.NETCore.Targets"
  "System.Security.Cryptography.Primitives" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.Primitives" --> "System.Runtime"
  "System.Security.Cryptography.Primitives" --> "System.Threading"
  "System.Security.Cryptography.Primitives" --> "System.Diagnostics.Debug"
  "System.Security.Cryptography.Primitives" --> "System.IO"
  "System.Security.Cryptography.Primitives" --> "System.Threading.Tasks"
  "System.Security.Cryptography.Primitives" --> "System.Globalization"
  "System.Diagnostics.Debug" --> "Microsoft.NETCore.Platforms"
  "System.Diagnostics.Debug" --> "System.Runtime"
  "System.Diagnostics.Debug" --> "Microsoft.NETCore.Targets"
  "System.IO.Compression" --> "System.Runtime.Extensions"
  "System.IO.Compression" --> "runtime.native.System.IO.Compression"
  "System.IO.Compression" --> "System.Runtime.Handles"
  "System.IO.Compression" --> "System.Resources.ResourceManager"
  "System.IO.Compression" --> "System.Runtime"
  "System.IO.Compression" --> "System.Threading"
  "System.IO.Compression" --> "System.Diagnostics.Debug"
  "System.IO.Compression" --> "System.Buffers"
  "System.IO.Compression" --> "runtime.native.System"
  "System.IO.Compression" --> "System.Collections"
  "System.IO.Compression" --> "Microsoft.NETCore.Platforms"
  "System.IO.Compression" --> "System.Runtime.InteropServices"
  "System.IO.Compression" --> "System.IO"
  "System.IO.Compression" --> "System.Threading.Tasks"
  "System.IO.Compression" --> "System.Text.Encoding"
  "System.Runtime.Extensions" --> "Microsoft.NETCore.Platforms"
  "System.Runtime.Extensions" --> "System.Runtime"
  "System.Runtime.Extensions" --> "Microsoft.NETCore.Targets"
  "runtime.native.System.IO.Compression" --> "Microsoft.NETCore.Platforms"
  "runtime.native.System.IO.Compression" --> "Microsoft.NETCore.Targets"
  "System.Runtime.Handles" --> "Microsoft.NETCore.Platforms"
  "System.Runtime.Handles" --> "System.Runtime"
  "System.Runtime.Handles" --> "Microsoft.NETCore.Targets"
  "runtime.native.System" --> "Microsoft.NETCore.Platforms"
  "runtime.native.System" --> "Microsoft.NETCore.Targets"
  "System.Runtime.InteropServices" --> "System.Runtime.Handles"
  "System.Runtime.InteropServices" --> "System.Runtime"
  "System.Runtime.InteropServices" --> "Microsoft.NETCore.Targets"
  "System.Runtime.InteropServices" --> "System.Reflection"
  "System.Runtime.InteropServices" --> "Microsoft.NETCore.Platforms"
  "System.Runtime.InteropServices" --> "System.Reflection.Primitives"
  "System.IO.FileSystem" --> "System.Runtime.Handles"
  "System.IO.FileSystem" --> "System.Runtime"
  "System.IO.FileSystem" --> "System.IO.FileSystem.Primitives"
  "System.IO.FileSystem" --> "Microsoft.NETCore.Platforms"
  "System.IO.FileSystem" --> "System.IO"
  "System.IO.FileSystem" --> "System.Threading.Tasks"
  "System.IO.FileSystem" --> "System.Text.Encoding"
  "System.IO.FileSystem" --> "Microsoft.NETCore.Targets"
  "System.IO.FileSystem.Primitives" --> "System.Runtime"
  "System.Threading.Timer" --> "Microsoft.NETCore.Platforms"
  "System.Threading.Timer" --> "System.Runtime"
  "System.Threading.Timer" --> "Microsoft.NETCore.Targets"
  "System.Reflection.Extensions" --> "Microsoft.NETCore.Platforms"
  "System.Reflection.Extensions" --> "System.Runtime"
  "System.Reflection.Extensions" --> "Microsoft.NETCore.Targets"
  "System.Reflection.Extensions" --> "System.Reflection"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Resources.ResourceManager"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Reflection.Extensions"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Runtime"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Threading"
  "System.Runtime.InteropServices.RuntimeInformation" --> "runtime.native.System"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Reflection"
  "System.Runtime.InteropServices.RuntimeInformation" --> "Microsoft.NETCore.Platforms"
  "System.Runtime.InteropServices.RuntimeInformation" --> "System.Runtime.InteropServices"
  "System.Collections.Concurrent" --> "System.Runtime.Extensions"
  "System.Collections.Concurrent" --> "System.Resources.ResourceManager"
  "System.Collections.Concurrent" --> "System.Runtime"
  "System.Collections.Concurrent" --> "System.Threading"
  "System.Collections.Concurrent" --> "System.Diagnostics.Tracing"
  "System.Collections.Concurrent" --> "System.Diagnostics.Debug"
  "System.Collections.Concurrent" --> "System.Collections"
  "System.Collections.Concurrent" --> "System.Reflection"
  "System.Collections.Concurrent" --> "System.Threading.Tasks"
  "System.Collections.Concurrent" --> "System.Globalization"
  "System.Security.Cryptography.X509Certificates" --> "System.Threading"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.X509Certificates" --> "System.Text.Encoding"
  "System.Security.Cryptography.X509Certificates" --> "System.IO.FileSystem"
  "System.Security.Cryptography.X509Certificates" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.X509Certificates" --> "System.Runtime.Handles"
  "System.Security.Cryptography.X509Certificates" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.X509Certificates" --> "System.Runtime"
  "System.Security.Cryptography.X509Certificates" --> "System.Collections"
  "System.Security.Cryptography.X509Certificates" --> "System.IO.FileSystem.Primitives"
  "System.Security.Cryptography.X509Certificates" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.X509Certificates" --> "System.Globalization.Calendars"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.Cng"
  "System.Security.Cryptography.X509Certificates" --> "System.Globalization"
  "System.Security.Cryptography.X509Certificates" --> "runtime.native.System.Security.Cryptography.OpenSsl"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.Csp"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.Encoding"
  "System.Security.Cryptography.X509Certificates" --> "runtime.native.System"
  "System.Security.Cryptography.X509Certificates" --> "System.IO"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.Algorithms"
  "System.Security.Cryptography.X509Certificates" --> "System.Security.Cryptography.OpenSsl"
  "System.Security.Cryptography.X509Certificates" --> "System.Diagnostics.Debug"
  "System.Security.Cryptography.X509Certificates" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.X509Certificates" --> "System.Runtime.Numerics"
  "System.Security.Cryptography.X509Certificates" --> "runtime.native.System.Net.Http"
  "System.Globalization.Calendars" --> "Microsoft.NETCore.Platforms"
  "System.Globalization.Calendars" --> "System.Runtime"
  "System.Globalization.Calendars" --> "Microsoft.NETCore.Targets"
  "System.Globalization.Calendars" --> "System.Globalization"
  "System.Security.Cryptography.Cng" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.Cng" --> "System.Runtime.Handles"
  "System.Security.Cryptography.Cng" --> "System.Security.Cryptography.Encoding"
  "System.Security.Cryptography.Cng" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.Cng" --> "System.Runtime"
  "System.Security.Cryptography.Cng" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.Cng" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.Cng" --> "System.IO"
  "System.Security.Cryptography.Cng" --> "System.Security.Cryptography.Algorithms"
  "System.Security.Cryptography.Cng" --> "System.Formats.Asn1"
  "System.Security.Cryptography.Cng" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.Cng" --> "System.Text.Encoding"
  "System.Security.Cryptography.Encoding" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.Encoding" --> "System.Runtime.Handles"
  "System.Security.Cryptography.Encoding" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.Encoding" --> "System.Runtime"
  "System.Security.Cryptography.Encoding" --> "System.Linq"
  "System.Security.Cryptography.Encoding" --> "System.Collections.Concurrent"
  "System.Security.Cryptography.Encoding" --> "System.Collections"
  "System.Security.Cryptography.Encoding" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.Encoding" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.Encoding" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.Encoding" --> "runtime.native.System.Security.Cryptography.OpenSsl"
  "System.Security.Cryptography.Encoding" --> "System.Text.Encoding"
  "System.Linq" --> "System.Runtime.Extensions"
  "System.Linq" --> "System.Resources.ResourceManager"
  "System.Linq" --> "System.Runtime"
  "System.Linq" --> "System.Diagnostics.Debug"
  "System.Linq" --> "System.Collections"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.opensuse.42.3-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.fedora.27-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.debian.9-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.ubuntu.18.04-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.fedora.28-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "runtime.native.System.Security.Cryptography.OpenSsl" --> "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl"
  "System.Security.Cryptography.Algorithms" --> "runtime.native.System.Security.Cryptography.OpenSsl"
  "System.Security.Cryptography.Algorithms" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.Algorithms" --> "System.Runtime.Handles"
  "System.Security.Cryptography.Algorithms" --> "System.Security.Cryptography.Encoding"
  "System.Security.Cryptography.Algorithms" --> "System.Runtime"
  "System.Security.Cryptography.Algorithms" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.Algorithms" --> "System.Collections"
  "System.Security.Cryptography.Algorithms" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.Algorithms" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.Algorithms" --> "runtime.native.System.Security.Cryptography.Apple"
  "System.Security.Cryptography.Algorithms" --> "System.IO"
  "System.Security.Cryptography.Algorithms" --> "System.Runtime.Numerics"
  "System.Security.Cryptography.Algorithms" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.Algorithms" --> "System.Text.Encoding"
  "runtime.native.System.Security.Cryptography.Apple" --> "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple"
  "System.Runtime.Numerics" --> "System.Runtime.Extensions"
  "System.Runtime.Numerics" --> "System.Resources.ResourceManager"
  "System.Runtime.Numerics" --> "System.Runtime"
  "System.Runtime.Numerics" --> "System.Globalization"
  "System.Formats.Asn1" --> "System.ValueTuple"
  "System.Formats.Asn1" --> "System.Memory"
  "System.Security.Cryptography.Csp" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.Csp" --> "System.Runtime.Handles"
  "System.Security.Cryptography.Csp" --> "System.Security.Cryptography.Encoding"
  "System.Security.Cryptography.Csp" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.Csp" --> "System.Runtime"
  "System.Security.Cryptography.Csp" --> "System.Threading"
  "System.Security.Cryptography.Csp" --> "System.Reflection"
  "System.Security.Cryptography.Csp" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.Csp" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.Csp" --> "System.IO"
  "System.Security.Cryptography.Csp" --> "System.Security.Cryptography.Algorithms"
  "System.Security.Cryptography.Csp" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.Csp" --> "System.Text.Encoding"
  "System.Security.Cryptography.OpenSsl" --> "System.Runtime.Extensions"
  "System.Security.Cryptography.OpenSsl" --> "System.Runtime.Handles"
  "System.Security.Cryptography.OpenSsl" --> "System.Security.Cryptography.Encoding"
  "System.Security.Cryptography.OpenSsl" --> "System.Resources.ResourceManager"
  "System.Security.Cryptography.OpenSsl" --> "System.Runtime"
  "System.Security.Cryptography.OpenSsl" --> "System.Collections"
  "System.Security.Cryptography.OpenSsl" --> "Microsoft.NETCore.Platforms"
  "System.Security.Cryptography.OpenSsl" --> "System.Runtime.InteropServices"
  "System.Security.Cryptography.OpenSsl" --> "System.IO"
  "System.Security.Cryptography.OpenSsl" --> "System.Security.Cryptography.Algorithms"
  "System.Security.Cryptography.OpenSsl" --> "System.Formats.Asn1"
  "System.Security.Cryptography.OpenSsl" --> "System.Runtime.Numerics"
  "System.Security.Cryptography.OpenSsl" --> "System.Security.Cryptography.Primitives"
  "System.Security.Cryptography.OpenSsl" --> "System.Text.Encoding"
  "runtime.native.System.Net.Http" --> "Microsoft.NETCore.Platforms"
  "runtime.native.System.Net.Http" --> "Microsoft.NETCore.Targets"
  "System.Diagnostics.Tools" --> "Microsoft.NETCore.Platforms"
  "System.Diagnostics.Tools" --> "System.Runtime"
  "System.Diagnostics.Tools" --> "Microsoft.NETCore.Targets"
  "System.Linq.Expressions" --> "System.Runtime.Extensions"
  "System.Linq.Expressions" --> "System.Reflection.Extensions"
  "System.Linq.Expressions" --> "System.Reflection.Emit.ILGeneration"
  "System.Linq.Expressions" --> "System.Resources.ResourceManager"
  "System.Linq.Expressions" --> "System.Runtime"
  "System.Linq.Expressions" --> "System.Threading"
  "System.Linq.Expressions" --> "System.Linq"
  "System.Linq.Expressions" --> "System.ObjectModel"
  "System.Linq.Expressions" --> "System.Diagnostics.Debug"
  "System.Linq.Expressions" --> "System.Reflection.Emit.Lightweight"
  "System.Linq.Expressions" --> "System.Collections"
  "System.Linq.Expressions" --> "System.Reflection"
  "System.Linq.Expressions" --> "System.IO"
  "System.Linq.Expressions" --> "System.Reflection.Emit"
  "System.Linq.Expressions" --> "System.Globalization"
  "System.Linq.Expressions" --> "System.Reflection.TypeExtensions"
  "System.Linq.Expressions" --> "System.Reflection.Primitives"
  "System.Reflection.Emit.ILGeneration" --> "System.Runtime"
  "System.Reflection.Emit.ILGeneration" --> "System.Resources.ResourceManager"
  "System.Reflection.Emit.ILGeneration" --> "System.Reflection.Primitives"
  "System.Reflection.Emit.ILGeneration" --> "System.Reflection"
  "System.ObjectModel" --> "System.Resources.ResourceManager"
  "System.ObjectModel" --> "System.Runtime"
  "System.ObjectModel" --> "System.Threading"
  "System.ObjectModel" --> "System.Diagnostics.Debug"
  "System.ObjectModel" --> "System.Collections"
  "System.Reflection.Emit.Lightweight" --> "System.Runtime"
  "System.Reflection.Emit.Lightweight" --> "System.Resources.ResourceManager"
  "System.Reflection.Emit.Lightweight" --> "System.Reflection.Emit.ILGeneration"
  "System.Reflection.Emit.Lightweight" --> "System.Reflection"
  "System.Reflection.Emit.Lightweight" --> "System.Reflection.Primitives"
  "System.Reflection.Emit" --> "System.Resources.ResourceManager"
  "System.Reflection.Emit" --> "System.Reflection.Emit.ILGeneration"
  "System.Reflection.Emit" --> "System.Runtime"
  "System.Reflection.Emit" --> "System.Reflection"
  "System.Reflection.Emit" --> "System.Runtime.InteropServices"
  "System.Reflection.Emit" --> "System.IO"
  "System.Reflection.Emit" --> "System.Reflection.Primitives"
  "System.Reflection.TypeExtensions" --> "System.Runtime.Extensions"
  "System.Reflection.TypeExtensions" --> "System.Resources.ResourceManager"
  "System.Reflection.TypeExtensions" --> "System.Runtime"
  "System.Reflection.TypeExtensions" --> "System.Linq"
  "System.Reflection.TypeExtensions" --> "System.Diagnostics.Debug"
  "System.Reflection.TypeExtensions" --> "System.Reflection"
  "System.Reflection.TypeExtensions" --> "System.Diagnostics.Contracts"
  "System.Reflection.TypeExtensions" --> "System.Reflection.Primitives"
  "System.Diagnostics.Contracts" --> "System.Runtime"
  "System.Net.Primitives" --> "Microsoft.NETCore.Platforms"
  "System.Net.Primitives" --> "System.Runtime.Handles"
  "System.Net.Primitives" --> "System.Runtime"
  "System.Net.Primitives" --> "Microsoft.NETCore.Targets"
  "System.Xml.XDocument" --> "System.Runtime.Extensions"
  "System.Xml.XDocument" --> "System.Resources.ResourceManager"
  "System.Xml.XDocument" --> "System.Runtime"
  "System.Xml.XDocument" --> "System.Threading"
  "System.Xml.XDocument" --> "System.Xml.ReaderWriter"
  "System.Xml.XDocument" --> "System.Diagnostics.Debug"
  "System.Xml.XDocument" --> "System.Collections"
  "System.Xml.XDocument" --> "System.Reflection"
  "System.Xml.XDocument" --> "System.IO"
  "System.Xml.XDocument" --> "System.Diagnostics.Tools"
  "System.Xml.XDocument" --> "System.Globalization"
  "System.Xml.XDocument" --> "System.Text.Encoding"
  "System.Xml.ReaderWriter" --> "System.Threading.Tasks.Extensions"
  "System.Xml.ReaderWriter" --> "System.Runtime.Extensions"
  "System.Xml.ReaderWriter" --> "System.Resources.ResourceManager"
  "System.Xml.ReaderWriter" --> "System.Runtime"
  "System.Xml.ReaderWriter" --> "System.Diagnostics.Debug"
  "System.Xml.ReaderWriter" --> "System.Text.RegularExpressions"
  "System.Xml.ReaderWriter" --> "System.Collections"
  "System.Xml.ReaderWriter" --> "System.IO.FileSystem.Primitives"
  "System.Xml.ReaderWriter" --> "System.Runtime.InteropServices"
  "System.Xml.ReaderWriter" --> "System.IO"
  "System.Xml.ReaderWriter" --> "System.Threading.Tasks"
  "System.Xml.ReaderWriter" --> "System.Globalization"
  "System.Xml.ReaderWriter" --> "System.Text.Encoding"
  "System.Xml.ReaderWriter" --> "System.IO.FileSystem"
  "System.Xml.ReaderWriter" --> "System.Text.Encoding.Extensions"
  "System.Text.RegularExpressions" --> "System.Runtime.Extensions"
  "System.Text.RegularExpressions" --> "System.Resources.ResourceManager"
  "System.Text.RegularExpressions" --> "System.Runtime"
  "System.Text.RegularExpressions" --> "System.Threading"
  "System.Text.RegularExpressions" --> "System.Collections"
  "System.Text.RegularExpressions" --> "System.Globalization"
  "System.Text.Encoding.Extensions" --> "Microsoft.NETCore.Platforms"
  "System.Text.Encoding.Extensions" --> "System.Text.Encoding"
  "System.Text.Encoding.Extensions" --> "System.Runtime"
  "System.Text.Encoding.Extensions" --> "Microsoft.NETCore.Targets"
  "System.Console" --> "System.Runtime"
  "System.Console" --> "Microsoft.NETCore.Platforms"
  "System.Console" --> "System.IO"
  "System.Console" --> "System.Text.Encoding"
  "System.Console" --> "Microsoft.NETCore.Targets"
  "Microsoft.Win32.Primitives" --> "Microsoft.NETCore.Platforms"
  "Microsoft.Win32.Primitives" --> "System.Runtime"
  "Microsoft.Win32.Primitives" --> "Microsoft.NETCore.Targets"
  "System.Net.Sockets" --> "System.Runtime"
  "System.Net.Sockets" --> "Microsoft.NETCore.Platforms"
  "System.Net.Sockets" --> "System.IO"
  "System.Net.Sockets" --> "System.Net.Primitives"
  "System.Net.Sockets" --> "System.Threading.Tasks"
  "System.Net.Sockets" --> "Microsoft.NETCore.Targets"
  "System.Net.Http" --> "System.Threading"
  "System.Net.Http" --> "System.Diagnostics.Tracing"
  "System.Net.Http" --> "System.Threading.Tasks"
  "System.Net.Http" --> "System.IO.Compression"
  "System.Net.Http" --> "System.Text.Encoding"
  "System.Net.Http" --> "System.Security.Cryptography.Primitives"
  "System.Net.Http" --> "System.IO.FileSystem"
  "System.Net.Http" --> "System.Runtime.Extensions"
  "System.Net.Http" --> "System.Runtime.Handles"
  "System.Net.Http" --> "System.Resources.ResourceManager"
  "System.Net.Http" --> "System.Runtime"
  "System.Net.Http" --> "System.Runtime.WindowsRuntime"
  "System.Net.Http" --> "System.Collections"
  "System.Net.Http" --> "System.Runtime.InteropServices"
  "System.Net.Http" --> "System.Security.Cryptography.X509Certificates"
  "System.Net.Http" --> "System.Net.Primitives"
  "System.Net.Http" --> "System.Globalization"
  "System.Net.Http" --> "System.Globalization.Extensions"
  "System.Net.Http" --> "runtime.native.System.Security.Cryptography.OpenSsl"
  "System.Net.Http" --> "System.Security.Cryptography.Encoding"
  "System.Net.Http" --> "Microsoft.Win32.Primitives"
  "System.Net.Http" --> "runtime.native.System"
  "System.Net.Http" --> "System.IO"
  "System.Net.Http" --> "System.Security.Cryptography.Algorithms"
  "System.Net.Http" --> "System.Security.Cryptography.OpenSsl"
  "System.Net.Http" --> "System.Diagnostics.DiagnosticSource"
  "System.Net.Http" --> "System.Diagnostics.Debug"
  "System.Net.Http" --> "Microsoft.NETCore.Platforms"
  "System.Net.Http" --> "runtime.native.System.Net.Http"
  "System.Net.Http" --> "System.Text.Encoding.Extensions"
  "System.Runtime.WindowsRuntime" --> "System.Runtime.Extensions"
  "System.Runtime.WindowsRuntime" --> "System.Resources.ResourceManager"
  "System.Runtime.WindowsRuntime" --> "System.Runtime"
  "System.Runtime.WindowsRuntime" --> "System.Threading"
  "System.Runtime.WindowsRuntime" --> "System.ObjectModel"
  "System.Runtime.WindowsRuntime" --> "System.Diagnostics.Debug"
  "System.Runtime.WindowsRuntime" --> "Microsoft.NETCore.Platforms"
  "System.Runtime.WindowsRuntime" --> "System.Runtime.InteropServices"
  "System.Runtime.WindowsRuntime" --> "System.IO"
  "System.Runtime.WindowsRuntime" --> "System.Threading.Tasks"
  "System.Runtime.WindowsRuntime" --> "System.Globalization"
  "System.Globalization.Extensions" --> "System.Runtime.Extensions"
  "System.Globalization.Extensions" --> "System.Resources.ResourceManager"
  "System.Globalization.Extensions" --> "System.Runtime"
  "System.Globalization.Extensions" --> "Microsoft.NETCore.Platforms"
  "System.Globalization.Extensions" --> "System.Runtime.InteropServices"
  "System.Globalization.Extensions" --> "System.Globalization"
  "System.IO.Compression.ZipFile" --> "System.Runtime.Extensions"
  "System.IO.Compression.ZipFile" --> "System.Resources.ResourceManager"
  "System.IO.Compression.ZipFile" --> "System.Runtime"
  "System.IO.Compression.ZipFile" --> "System.Buffers"
  "System.IO.Compression.ZipFile" --> "System.IO.FileSystem.Primitives"
  "System.IO.Compression.ZipFile" --> "System.IO"
  "System.IO.Compression.ZipFile" --> "System.IO.Compression"
  "System.IO.Compression.ZipFile" --> "System.Text.Encoding"
  "System.IO.Compression.ZipFile" --> "System.IO.FileSystem"
@enduml