@startuml
skinparam defaultFontName Arial

  "Newtonsoft.Json" --> "System.ComponentModel.TypeConverter"
  "Newtonsoft.Json" --> "Microsoft.CSharp"
  "Newtonsoft.Json" --> "System.Xml.XmlDocument"
  "Newtonsoft.Json" --> "System.Runtime.Serialization.Primitives"
  "Newtonsoft.Json" --> "NETStandard.Library"
  "Newtonsoft.Json" --> "System.Runtime.Serialization.Formatters"
  "System.ComponentModel.TypeConverter" --> "System.ComponentModel.Primitives"
  "System.ComponentModel.TypeConverter" --> "System.Collections.Specialized"
  "System.ComponentModel.TypeConverter" --> "System.Collections.NonGeneric"
  "System.ComponentModel.TypeConverter" --> "System.Collections"
  "System.ComponentModel.TypeConverter" --> "System.Globalization"
  "System.ComponentModel.TypeConverter" --> "System.Runtime"
  "System.ComponentModel.TypeConverter" --> "System.Resources.ResourceManager"
  "System.ComponentModel.TypeConverter" --> "System.ComponentModel"
  "System.ComponentModel.TypeConverter" --> "System.Reflection"
  "System.ComponentModel.TypeConverter" --> "System.Threading"
  "System.ComponentModel.TypeConverter" --> "System.Reflection.Primitives"
  "System.ComponentModel.TypeConverter" --> "System.Reflection.TypeExtensions"
  "System.ComponentModel.TypeConverter" --> "System.Linq"
  "System.ComponentModel.TypeConverter" --> "System.Reflection.Extensions"
  "System.ComponentModel.TypeConverter" --> "System.Runtime.Extensions"
  "Microsoft.CSharp" --> "System.Reflection.TypeExtensions"
  "Microsoft.CSharp" --> "NETStandard.Library"
  "Microsoft.CSharp" --> "System.Dynamic.Runtime"
  "System.Xml.XmlDocument" --> "System.IO"
  "System.Xml.XmlDocument" --> "System.Collections"
  "System.Xml.XmlDocument" --> "System.Globalization"
  "System.Xml.XmlDocument" --> "System.Diagnostics.Debug"
  "System.Xml.XmlDocument" --> "System.Runtime"
  "System.Xml.XmlDocument" --> "System.Xml.ReaderWriter"
  "System.Xml.XmlDocument" --> "System.Resources.ResourceManager"
  "System.Xml.XmlDocument" --> "System.Threading"
  "System.Xml.XmlDocument" --> "System.Text.Encoding"
  "System.Xml.XmlDocument" --> "System.Runtime.Extensions"
  "System.Runtime.Serialization.Primitives" --> "System.Runtime"
  "System.Runtime.Serialization.Primitives" --> "System.Resources.ResourceManager"
  "NETStandard.Library" --> "System.Runtime.Numerics"
  "NETStandard.Library" --> "System.Diagnostics.Tracing"
  "NETStandard.Library" --> "System.Globalization"
  "NETStandard.Library" --> "System.Diagnostics.Debug"
  "NETStandard.Library" --> "System.Xml.XDocument"
  "NETStandard.Library" --> "System.Text.Encoding"
  "NETStandard.Library" --> "System.Security.Cryptography.X509Certificates"
  "NETStandard.Library" --> "System.Linq"
  "NETStandard.Library" --> "System.Net.Primitives"
  "NETStandard.Library" --> "System.IO.Compression"
  "NETStandard.Library" --> "System.Runtime.Extensions"
  "NETStandard.Library" --> "System.Diagnostics.Tools"
  "NETStandard.Library" --> "System.IO"
  "NETStandard.Library" --> "System.AppContext"
  "NETStandard.Library" --> "System.Runtime.InteropServices"
  "NETStandard.Library" --> "System.Linq.Expressions"
  "NETStandard.Library" --> "System.Net.Sockets"
  "NETStandard.Library" --> "System.Security.Cryptography.Encoding"
  "NETStandard.Library" --> "System.Console"
  "NETStandard.Library" --> "System.IO.Compression.ZipFile"
  "NETStandard.Library" --> "System.Reflection"
  "NETStandard.Library" --> "System.Threading"
  "NETStandard.Library" --> "System.Security.Cryptography.Primitives"
  "NETStandard.Library" --> "System.ObjectModel"
  "NETStandard.Library" --> "System.Collections"
  "NETStandard.Library" --> "System.Globalization.Calendars"
  "NETStandard.Library" --> "Microsoft.NETCore.Platforms"
  "NETStandard.Library" --> "System.Reflection.Primitives"
  "NETStandard.Library" --> "System.Runtime.Handles"
  "NETStandard.Library" --> "System.Reflection.Extensions"
  "NETStandard.Library" --> "System.Collections.Concurrent"
  "NETStandard.Library" --> "System.Xml.ReaderWriter"
  "NETStandard.Library" --> "System.Runtime.InteropServices.RuntimeInformation"
  "NETStandard.Library" --> "System.IO.FileSystem"
  "NETStandard.Library" --> "System.Text.RegularExpressions"
  "NETStandard.Library" --> "System.Runtime"
  "NETStandard.Library" --> "Microsoft.Win32.Primitives"
  "NETStandard.Library" --> "System.Net.Http"
  "NETStandard.Library" --> "System.Resources.ResourceManager"
  "NETStandard.Library" --> "System.Text.Encoding.Extensions"
  "NETStandard.Library" --> "System.Threading.Tasks"
  "NETStandard.Library" --> "System.Threading.Timer"
  "NETStandard.Library" --> "System.Security.Cryptography.Algorithms"
  "NETStandard.Library" --> "System.IO.FileSystem.Primitives"
@enduml